/*
  This code is generated by Fredy's SQL-Admin Tool visit http://www.hulmen.ch/admin
 


*/

package sql.fredy.ui; 

import java.util.Vector;
import java.sql.Timestamp;


public class QueryBeanNotes {


private int id;

public void setId(int v){
	this.id = v;
}

public int getId(){
	 return id;
}

private java.sql.Timestamp runat;

public void setRunat(java.sql.Timestamp v){
	this.runat = v;
}

public java.sql.Timestamp getRunat(){
	 return runat;
}

private String title;

public void setTitle(String v){
	this.title = v;
}

public String getTitle(){
	 return title;
}

private String note;

public void setNote(String v){
	this.note = v;
}

public String getNote(){
	 return note;
}

private int hashcode;

public void setHashcode(int v){
	this.hashcode = v;
}

public int getHashcode(){
	 return hashcode;
}
public Vector getVector() {
	Vector v = new Vector();
	v.addElement(getId());
	v.addElement((java.sql.Timestamp) getRunat());
	v.addElement((String) getTitle());
	v.addElement((String) getNote());
	v.addElement(getHashcode());

	return v;
}

}